### ISSUE TITLE
Don't quit an application when the last window is closed

### ISSUE THREAD

**Issue by andreypolyak** [pyloid/pyloid#13]
Hi there,

I really like your library and plan to use it in my app.

However, I noticed that when using `single_instance=False`, the application quits entirely when the last window is closed. Would it be possible to add an option to disable this behavior?

Thanks!

**Comment by aesthetics-of-record** [comment]
The single_instance option prevents multiple apps from running.

If single_instance is False, multiple apps can run simultaneously.

So it is an option unrelated to Windows.

So, if the problem is that it "quits" when you press the close button of the frame, You can create a custom title bar


### python

```python
class customAPI(PyloidAPI):
    @Bridge()
    def customClose(self):
        if len(self.app.get_windows()) > 1:
            self.window.close()
        else:
            self.window.hide()


win = app.create_window("Pyloid", js_apis=[customAPI()])
```

### js
```js
window.pyloid.customAPI.customClose()
```

It is recommended to write code that shows the main window when the system tray icon is clicked.

Please refer to this article
https://docs.pyloid.com/guides/window-customization

You can use this code starting from version 0.17.4 or higher.
```
# Windows OS
./venv-pyloid/Script/pip install --upgrade pyloid

# Or Remove venv-pyloid -> npm run init
```

Thanks for your Issue!
