### ISSUE TITLE
How to mount a directory as static url in webview ?

### ISSUE THREAD

**Issue by baseplate-admin** [pyloid/pyloid#19]
Hi, i have this following [repository](https://github.com/baseplate-admin/pyloid-test),

When i run these commands

1. `npm run build`
2. `python ./src-pyloid/main.py`

It doesn't show anything. 
I think the client folder needs to be mounted. I can do it from lets say `djagno`/`flask`/`bottle`, but i was wondering if `pyloid` should handle this use case

**Comment by aesthetics-of-record** [comment]
[boilerplate guide](https://docs.pyloid.com/guides/custom-boilerpalte)

you can see custom boilerplate guide. 
I have a feeling it might be helpful to you.


The build is done through Pyinstaller.

So, you can confirm that the spec file can include all binary files necessary to build.

You can also check the mounted path.

To access the mounted path
Use the ```get_production_path()``` function.


I looked at some of your code.

Based on that standard, you can handle it like this.

1. spec file (your os spec file)

If your static files (index.html, assets, etc.) are in "build/client/"

```python
a = Analysis(['src-pyloid/main.py'],
            pathex=[],
            binaries=[],
            #################################
            # Update this
            datas=[('src-pyloid/icons/', 'icons/'),
            ('build/client/', 'build/client/'),
            ],
            # [(file_path), (production_path)]
            #################################
            hiddenimports=[],
            hookspath=[],
            hooksconfig={},
            runtime_hooks=[],
            excludes=['PySide6.QtQml', 'PySide6.QtTest', 'PySide6.Qt3D', 'PySide6.QtSensors', 'PySide6.QtCharts', 'PySide6.QtGraphs', 'PySide6.QtDataVisualization', 'PySide6.QtQuick', 'PySide6.QtDesigner', 'PySide6.QtUiTools', 'PySide6.QtHelp'],
            win_no_prefer_redirects=False,
            win_private_assemblies=False,
            cipher=block_cipher,
            noarchive=False)
```


2. main.py file
```python
if is_production():
    window.load_file(os.path.join(get_production_path(), "build/client/index.html"))
else:
    window.load_url("http://localhost:5173")
```



Thank you for your interest!

Issues are always welcome.

And for reference, I created a prototype of a tool that allows you to easily customize the build process.

I have a lot of work to do at the moment, so I plan to organize it next week and develop tools for such complex problems.

We are also planning on doing typescript api package, etc., which you mentioned.

---

If this issue is a bit complicated or doesn't work well, you can upload a new issue with an additional explanation.
