### ISSUE TITLE
High consumption resources CPU and Memory in boilerplate

### ISSUE THREAD

**Issue by camux** [pyloid/pyloid#3]
Hi, 
I detected that only running basic bolierplate react project (without changes) in my PC (Core i7 12gen, 16 GB, and NVME), Ubuntu 24.04 has relatively high resource consumption, instead a Tauri project with many class, components and database connection, etc, please see attach image Tauri project vs Pyloid (Boilerplate)

Tauri
![Screenshot from 2024-10-12 16-57-50](https://github.com/user-attachments/assets/56e47024-54e6-4b71-b89d-8c8c4d1eeb15)

Pyloid (React Boilerplate)
![Screenshot from 2024-10-12 17-04-12](https://github.com/user-attachments/assets/05d381c8-afd2-4d08-bcbd-4962d0122e04)

Indeed Pyloid consume more resources that gnome-shell !

I think that Qt6 Web engine can be the problem, not python or Pyloid.

https://forum.qt.io/topic/147955/qtweb-engine-high-cpu-usage/5

https://community.nxp.com/t5/i-MX-Processors/HIgh-CPU-utilization-on-Qt6-application/m-p/1654517#M206249

I think that there is two possible solutions, I am not sure ;)

1. Use https://webkitgtk.org/ as option to QtWebEngine, maybe I can help with this, It would be add to in toml file the webview engine option for example:
web-engine = "gtk" or web-engine = "Qt6"

2. Use this library built Rust for python.

[Pywry](https://github.com/OpenBB-finance/pywry)

I can try to help with pull request for this option, and continue collaborating in this project

Thanks for advance

**Comment by aesthetics-of-record** [comment]
Hi,

Thank you for your detailed feedback and for your interest in the project.

You’ve raised some valid points regarding QtWebEngine. While it indeed supports the latest web technologies and offers robust performance, it does tend to consume more CPU and memory, which might not be ideal for lightweight applications. The larger bundle size is also a factor that cannot be overlooked.

In the early stages, I did consider using WebKitGTK, but given the project's focus on providing high performance, AI capabilities, and compatibility with Python, as well as ensuring a consistent cross-platform experience, WebKitGTK seemed to introduce more complexity.

You’re right in noting that Tauri, by using different engines per operating system, can be more efficient in terms of memory usage and bundle size. However, it does face challenges in offering a uniform experience across platforms. This is particularly evident in Linux, where projects that rely on WebRTC or demand high performance have reported slowdowns.

For now, I’m continuing development with QtWebEngine due to its comprehensive feature set, but I remain open to exploring other options in the future. If QtWebKit were to be revived, I would definitely consider it. However, at this point, further exploration of WebKitGTK or other engines is on hold.

Once again, I truly appreciate your input and would welcome any future collaboration or contributions to the project.

**Comment by baseplate-admin** [comment]
Hey @aesthetics-of-record, i know this was closed, but could you consider building on top of `pywebview`? To my knowledge `pywebview` uses the same approach as `tauri`. Building on top of `pywebview` might solve this large bundle issue.

**Comment by aesthetics-of-record** [comment]
@baseplate-admin 

it's not currently on the roadmap.

I've been thinking about that for a long time.
However, I think that using multiple webviews would increase complexity, both in terms of performance and feature implementation.

Initially, I thought about reducing the bundle size with such native webviews, but there is a limit to what I can do alone, and the moment I introduce them, I have to implement the libraries I currently rely on, which increases the complexity by more than 5 times.

Existing lightweight desktop app frameworks use native webviews to reduce the bundle size, but in practice, users are forced to write different code for each platform when coding with the framework. 

Especially when it comes to advanced web APIs like webRTC, Tauri requires a different approach for mac, window, and linux.
For pywebview, such advanced api's are not available due to platform compatibility issues.

As far as I know, there is a way to embed and bundle webviews directly in tauri for such consistency, but in that case, the bundle size becomes larger than electron, etc.

That's why I designed it with the goal of simplicity, to be able to have the same developer experience on any OS with consistent code for any platform.
The benefit of having a single built-in webview is that it reduces complexity, making it easier to update and maintain the various built-in modules quickly.

Thank you for your interest.
